### ISSUE TITLE
Out of range with new dji "Fly" app txt file

### ISSUE THREAD

**Issue by lyapounov** [chrisvm/node-djiparsetxt#14]
On dji Fly app txt file, the call to parse_file returns

RangeError: index out of range
    at checkOffset (buffer.js:622:11)
    at Buffer.readUInt8 (buffer.js:660:5)
    at is_jpeg_soi (/datas/www/dji/node_modules/node-djiparsetxt/dist/services/FileParsingService.js:26:20)
    at FileParsingService.get_record_cache (/datas/www/dji/node_modules/node-djiparsetxt/dist/services/FileParsingService.js:110:28)
    at FileParsingService.parse_records (/datas/www/dji/node_modules/node-djiparsetxt/dist/services/FileParsingService.js:50:28)
    at Object.parse_file (/datas/www/dji/node_modules/node-djiparsetxt/dist/node-djiparsetxt.js:160:43)

**Comment by lyapounov** [comment]
here is the txt file

[fltest.txt](https://github.com/chrisvm/node-djiparsetxt/files/5057777/fltest.txt)

**Comment by chrisvm** [comment]
Thanks for the issue report, will work on it when I have some time between projects. Should be an easy fix.

**Comment by jfcisternasm** [comment]
Hi, i'm using this library and have same issue with dji fly files. How can i help?
